- assignment: 914847db77a76049db24285b6bb5ecd4
  section: ["Unit 0", "Welcome"]
  paths: ["0.0-welcome/**"]
  
- assignment: 6d5c0550a03968ef2d695a019b3665b4
  section: ["Unit 0", "Scratch Surprise"]
  paths: ["0.1-scratch-surprise/**"]
  
- assignment: 375329a52ba07d902bfea4305ec315db
  section: ["Unit 1 - Exploring", "Step-By-Step"]
  paths: ["1.1-step-by-step/**"]
  
- assignment: a90bc7ee50ddb00b325368ca4d68eb6a
  section: ["Unit 1 - Exploring", "10 Blocks"]
  paths: ["1.2-ten-blocks/**"]

- assignment: 6b51013423f9d47fa982718c771c7675
  section: ["Unit 1 - Exploring", "Debug It!"]
  paths: ["1.3-debug-it/**"]

- assignment: 7191743dff8544606c4beec5e6669f1d
  section: ["Unit 1 - Exploring", "About Me"]
  paths: ["1.4-about-me/**"]

- assignment: 2c94859440ff78f6c9b97f8c8a7a43b9
  section: ["Unit 2 - Animations", "Build-a-Band"]
  paths: ["2.1-build-a-band/**"]

- assignment: fb847d2b20ce0ef08af6f285693bd536
  section: ["Unit 2 - Animations", "Orange Square, Purple Circle"]
  paths: ["2.2-orange-square/**"]

- assignment: 37030feb77d03c240bfe99a97f408637
  section: ["Unit 2 - Animations", "It's Alive"]
  paths: ["2.3-its-alive/**"]

- assignment: 63236aa57c810c35e620ff837191ded2
  section: ["Unit 2 - Animations", "Debug It!"]
  paths: ["2.4-debug-it/**"]

- assignment: e9f4e9122291b8f8b82cee87b43e6538
  section: ["Unit 2 - Animations", "Music Video"]
  paths: ["2.5-music-video/**"]
  
- assignment: e0318e2023a5776bdb533ff6df2d9fe5
  section: ["Unit 3 - Characters", "Characters"]
  paths: ["3.1-characters/**"]
  
- assignment: a6a11509dc189045e98d3e4ffed1c9d3
  section: ["Unit 3 - Characters", "Conversations"]
  paths: ["3.2-conversations/**"]
  
- assignment: fb391d1f7078a3a839989563e3a6800d
  section: ["Unit 3 - Characters", "Scenes"]
  paths: ["3.3-scenes/**"]
  
- assignment: 38e347e2ccd04a2ca9105cb70c58bb9e
  section: ["Unit 3 - Characters", "Debug It!"]
  paths: ["3.4-debug-it/**"]
  
- assignment: 28b0d5cd3bed5d0a7353da17ca8590fb
  section: ["Unit 4 - Games", "Keeping Score"]
  paths: ["4.1-keeping-score/**"]
  
- assignment: aee503b8afb7e00986ed9049d10ded92
  section: ["Unit 4 - Games", "Starter Games"]
  paths: ["4.2-starter-games/**"]
- assignment: aee503b8afb7e00986ed9049d10ded92
  section: ["Unit 4 - Games", "Extensions"]
  paths: ["4.2-starter-games/**"]
  
- assignment: fb61a54adb508ff337e385a9ff27f598
  section: ["Unit 4 - Games", "Interactions"]
  paths: ["4.3-interactions/**"]
  
- assignment: 282ef07e7b445235757421c3cc802317
  section: ["Unit 4 - Games", "Debug It!"]
  paths: ["4.4-debug-it/**"]