- assignment: 914847db77a76049db24285b6bb5ecd4
  section:  ["Unit 0", "Welcome"]
  paths: ["0.0-welcome/**"]
  
- assignment: 6d5c0550a03968ef2d695a019b3665b4
  section:  ["Unit 0", "Scratch Surprise"]
  paths: ["0.1-scratch-surprise/**"]
  
- assignment: 375329a52ba07d902bfea4305ec315db
  section:  ["Unit 1", "Step-By-Step"]
  paths: ["1.1-step-by-step/**"]
  
- assignment: a90bc7ee50ddb00b325368ca4d68eb6a
  section:  ["Unit 1", "10 Blocks"]
  paths: ["1.2-ten-blocks/**"]